"""
A6 – Contextual Retrieval Chatbot (Streamlit)

Task 3:
  1) Simple web app with chat interface
  2) Answers questions about Chapter 6 (Neural Networks)
  3) Backend uses Contextual Retrieval (enriched chunks + FAISS + Claude Haiku)
  4) Displays generated answer AND cites the source chunk(s) used

Run from project root:
    streamlit run A6/app/app.py
"""

import os, re, pickle
import streamlit as st
import faiss
import anthropic
from dotenv import load_dotenv
from langchain_community.document_loaders import PyMuPDFLoader
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
from sentence_transformers import SentenceTransformer

# ── Config ──────────────────────────────────────────────────────────────────
load_dotenv(os.path.join(os.path.dirname(__file__), "../../.env"))

PDF_PATH   = os.path.join(os.path.dirname(__file__), "../data/6.pdf")
CACHE_PATH = os.path.join(os.path.dirname(__file__), "../models/enriched_chunks.pkl")
TITLE      = "Chapter 6: Neural Networks"
TOP_K      = 3


# ── Data cleaning (mirrors the notebook) ────────────────────────────────────
def clean_page(text: str) -> str:
    ligatures = {
        "ﬁ": "fi", "ﬀ": "ff", "": "ffi", "ﬂ": "fl", "ﬄ": "ffl",
        "\ufb01": "fi", "\ufb02": "fl", "\ufb00": "ff",
        "\ufb03": "ffi", "\ufb04": "ffl",
    }
    for ch, rep in ligatures.items():
        text = text.replace(ch, rep)

    text = re.sub(r"(\w+)-\n(\w)", r"\1\2", text)
    text = re.sub(r"^\d{1,3}\n+CHAPTER\s+\d+\s*\n+[•·]\s*\n+[A-Z ,]+\n+", "", text, flags=re.MULTILINE)
    text = re.sub(r"(?m)^\d{1,3}\s*$", "", text)
    text = re.sub(r"(?m)^(Figure|Table)\s+\d+\.\d+.*$", "", text)
    text = re.sub(r"(?m)^\(\d+\.\d+\)\s*$", "", text)

    cleaned = []
    for line in text.split("\n"):
        s = line.strip()
        words = s.split()
        if (
            1 <= len(words) <= 3
            and s == s.lower()
            and s[-1:] not in ".?!:,"
            and not re.search(r"\d", s)
            and not s.startswith("•")
        ):
            continue
        cleaned.append(line)
    text = "\n".join(cleaned)

    text = re.sub(r"\n{3,}", "\n\n", text)
    text = re.sub(r"[ \t]{2,}", " ", text)
    text = "\n".join(line.rstrip() for line in text.split("\n"))
    return text.strip()


# ── Build / load index (cached across reruns) ────────────────────────────────
@st.cache_resource(show_spinner="Loading and indexing Chapter 6…")
def build_index():
    # Load PDF
    raw_docs = PyMuPDFLoader(PDF_PATH).load()
    docs = [Document(page_content=clean_page(d.page_content), metadata=d.metadata) for d in raw_docs]
    full_doc = "\n\n".join(d.page_content for d in docs)

    splitter    = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
    chunks      = splitter.split_documents(docs)
    chunk_texts = [c.page_content for c in chunks]

    embed_model = SentenceTransformer("all-MiniLM-L6-v2")

    # Use pre-enriched chunks if available (generated by the notebook)
    if os.path.exists(CACHE_PATH):
        with open(CACHE_PATH, "rb") as f:
            enriched_texts = pickle.load(f)
    else:
        client = anthropic.Anthropic()
        enriched_texts = []
        progress = st.progress(0, text="Enriching chunks with Claude (first run only)…")
        for i, chunk in enumerate(chunk_texts):
            prompt = (
                f"Title: {TITLE}\n\n{full_doc[:4000]}\n\nChunk:\n{chunk}\n\n"
                "Provide brief context (1-2 sentences) explaining what this chunk "
                "discusses in relation to the full document. "
                'Format: "This chunk from [title] discusses [explanation]."'
            )
            resp = client.messages.create(
                model="claude-haiku-4-5-20251001",
                max_tokens=150,
                messages=[{"role": "user", "content": prompt}],
            )
            enriched_texts.append(f"{resp.content[0].text.strip()}\n\n{chunk}")
            progress.progress((i + 1) / len(chunk_texts))
        progress.empty()
        os.makedirs(os.path.dirname(CACHE_PATH), exist_ok=True)
        with open(CACHE_PATH, "wb") as f:
            pickle.dump(enriched_texts, f)

    embs  = embed_model.encode(enriched_texts, convert_to_numpy=True)
    index = faiss.IndexFlatL2(embs.shape[1])
    index.add(embs.astype("float32"))

    return embed_model, index, enriched_texts


def answer_question(question, embed_model, index, enriched_texts):
    q_emb = embed_model.encode([question], convert_to_numpy=True).astype("float32")
    _, idxs = index.search(q_emb, TOP_K)
    sources = [enriched_texts[i] for i in idxs[0]]
    context = "\n\n---\n\n".join(sources)

    resp = anthropic.Anthropic().messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=400,
        messages=[{
            "role": "user",
            "content": (
                "Answer the question using ONLY the context provided below. "
                "Be concise and accurate.\n\n"
                f"Context:\n{context}\n\n"
                f"Question: {question}"
            ),
        }],
    )
    return resp.content[0].text.strip(), sources


# ── Streamlit UI ─────────────────────────────────────────────────────────────
st.set_page_config(page_title="Neural Networks QA", page_icon="🧠", layout="wide")

st.title("🧠 Neural Networks QA — Chapter 6")
st.caption(
    "**Retriever:** `all-MiniLM-L6-v2`  ·  "
    "**Generator:** `claude-haiku-4-5-20251001`  ·  "
    "**Method:** Contextual Retrieval  ·  "
    "Source: Jurafsky & Martin, SLP3"
)

embed_model, index, enriched_texts = build_index()

if "messages" not in st.session_state:
    st.session_state.messages = []

# Render chat history
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg["role"] == "assistant":
            with st.expander("📄 Source chunks used for this answer"):
                for i, src in enumerate(msg.get("sources", []), 1):
                    st.markdown(f"**Chunk {i}**")
                    st.text(src[:600] + ("…" if len(src) > 600 else ""))
                    st.divider()

# Chat input
if prompt := st.chat_input("Ask a question about Chapter 6: Neural Networks…"):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        with st.spinner("Retrieving and generating answer…"):
            answer, sources = answer_question(prompt, embed_model, index, enriched_texts)
        st.markdown(answer)
        with st.expander("📄 Source chunks used for this answer"):
            for i, src in enumerate(sources, 1):
                st.markdown(f"**Chunk {i}**")
                st.text(src[:600] + ("…" if len(src) > 600 else ""))
                st.divider()

    st.session_state.messages.append({
        "role": "assistant",
        "content": answer,
        "sources": sources,
    })
